# Optional: local preview only. GitHub Pages builds the site automatically;
# you do NOT need Ruby/Bundler unless you want to preview locally.
#
# Local preview:
#   cd docs && bundle install && bundle exec jekyll serve
#
source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "webrick"
